FROM node:16-alpine

RUN apk add --no-cache libc6-compat

# add turborepo
RUN yarn global add turbo

WORKDIR /app

#add strapi
RUN yarn global add @strapi/strapi@4.11.5

VOLUME [ "/app/apps/backend/public/uploads"]

# Copy source files
COPY . .

RUN yarn install --network-timeout 100000
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
RUN yarn build --scope backend


CMD ["yarn", "start", "--scope", "backend"]