FROM node:18-buster-slim

WORKDIR /app

ARG NEXT_PUBLIC_SERVER_URI=
ARG NEXT_PUBLIC_MAPS_API_KEY=
ARG NEXT_PUBLIC_SQUARE_ACCESS_TOKEN=
ARG NEXT_PUBLIC_LOCATION_ID=
ARG NEXT_PUBLIC_APPLICATION_ID=
ARG NEXT_PUBLIC_SERVER_API=
ARG NEXT_PUBLIC_SQUARE_ENVIRONMENT=
ENV NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI}
ENV NEXT_PUBLIC_MAPS_API_KEY=${NEXT_PUBLIC_MAPS_API_KEY}
ENV NEXT_PUBLIC_SQUARE_ACCESS_TOKEN=${NEXT_PUBLIC_SQUARE_ACCESS_TOKEN}
ENV NEXT_PUBLIC_LOCATION_ID=${NEXT_PUBLIC_LOCATION_ID}
ENV NEXT_PUBLIC_APPLICATION_ID=${NEXT_PUBLIC_APPLICATION_ID}
ENV NEXT_PUBLIC_SERVER_API=${NEXT_PUBLIC_SERVER_API}
ENV NEXT_PUBLIC_SQUARE_ENVIRONMENT=${NEXT_PUBLIC_SQUARE_ENVIRONMENT}

COPY . .

RUN yarn install --timeout 1000000

RUN yarn build

RUN echo 'NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI}\n\
  NEXT_PUBLIC_MAPS_API_KEY=${NEXT_PUBLIC_MAPS_API_KEY}\n\
  NEXT_PUBLIC_SQUARE_ACCESS_TOKEN=${NEXT_PUBLIC_SQUARE_ACCESS_TOKEN}\n\
  NEXT_PUBLIC_LOCATION_ID=${NEXT_PUBLIC_LOCATION_ID}\n\
  NEXT_PUBLIC_APPLICATION_ID=${NEXT_PUBLIC_APPLICATION_ID}\n\
  NEXT_PUBLIC_SERVER_API=${NEXT_PUBLIC_SERVER_API}\n\
  NEXT_PUBLIC_SQUARE_ENVIRONMENT=${NEXT_PUBLIC_SQUARE_ENVIRONMENT}'\
  >> .env

EXPOSE 3000

CMD [ "yarn", "workspace", "frontend", "start" ]
